spring:
  rabbitmq:
    host: 192.168.72.128
    port: 5672
    username: guest
    password: guest
server:
  port: 8600
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/